### PR TITLE
WIP: Update to Irelia 0.5

### PR DESCRIPTION
**Pull request by AlsoSylv**
Currently, there are two issues with the PR:
1. Sometimes certain types will show up as `Array` instead of as their custom type name
2. The order of endpoints is random, because Irelia uses a hashmap for it's types, this can be fixed before merge if required

### CODE REVIEW

**Comment by AlsoSylv** [comment]
Issue 1 has been fixed, issue two would need to be fixed in Irelia, but the code changes should be ready for review

**Comment by AlsoSylv** [comment]
Upon further inspection, serde_json::Map does not work here, so some other ordered map will need to be used

**Comment by AlsoSylv** [comment]
With that final commit, this should match the current behavior 1:1

**Review by BlossomiShymae — CHANGES_REQUESTED** [review]
Lines 77, 80, 132, and 171 for `lcu_schema.rs` give `E0308`.

**Comment by BlossomiShymae** [comment]
LGTM. :3

**Pull request merged**
